services:
  pg:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORD: smart
      POSTGRES_DB: smart_order
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - pg

volumes:
  pgdata:
